### ISSUE TITLE
setup.py has errors

### ISSUE THREAD

**Issue by tjlang** [nguy/PyRadarMet#1] opened 2014-11-21 22:05 UTC
"python setup.py install" fails on the following line:
datafiles = glob.glob(os.path.join(pathout,'*'))
because pathout has not been defined yet. What is it supposed to be?

**Comment by nguy** [comment] 2015-02-26 20:25
@tjlang I've been looking at this a little more today.  It seems to be a widespread issue without good solutions.  Did you find a workaround?

**Comment by tjlang** [comment] 2015-02-27 05:25
Here is what I recommend. Have the user define the path to the DEM data by editing the DEM_DATA line in BeamBlock.py:
# Set up the data directory for DEM files
#DEM_DATADIR = os.sep.join([os.path.dirname(__file__), 'data'])
DEM_DATADIR = '/Users/tjlang/Downloads/PyRadarMet/pyradarmet/data' #Change as needed

Now go into setup.py and delete any references to the package data.
1. First change the following line to avoid syntax errors in Python 2.6 (or earlier):
package_dirs={'': 'pyradarmet'} #was package_dirs={'pyradarmet'}
2. Comment out the DEM_DATADIR definition.
3. Delete the following lines:
      package_data={'pyradarmet': ['data/*']},
      include_package_data=True,

Then install as usual. Now the DEMs aren't copied to a whole new directory, and if the path ever changes a quick edit to BeamBlock.py and subsequent reinstall (now much faster that we aren't copying 100s of MB of data) gets us back to status quo ante.

I tested this and it seems to work - created the following image with the newly reconfigured package:
![figure_1](https://cloud.githubusercontent.com/assets/3036387/6407852/6602f18e-be0e-11e4-825a-50bd0fb7a5d2.png)

**Comment by tjlang** [comment] 2015-02-27 05:32
Installing the data along with the package is more elegant and less breakable, but in this case I think the 100s of MB changes the equation. The files are just too large - let the user put the data where they need them to be, and only install the code itself.

Note: It's likely possible to be clever and somehow have the DEM_DATADIR get set in setup.py and not BeamBlock.py (or perhaps set it in some extra file, named edit_me_before_installing.py). That might simplify the new install process slightly.

**Comment by kmuehlbauer** [comment] 2015-03-06 07:38
Just as a addition to possible solutions:

I had a similar task of fetching data from webresources and extract to some directory. I found quite a bunch of locations where GNU "make" is used for that. A working Makefile which gathers the DEM archives and extracts the .dem and .hdr files to the appropriate folders is attached below.

It uses `wget` for download and some special `tar` options to gain the lowercase output. If you put the `Makefile` into `pyradarmet` folder you can run it by `make extract_dem`. It will download all needed files to gz-subfolder and extract the DEM-files (.dem, .hdr) to data-folder.

As long as the FTP-resource stays the same and wget and tar are available on the client system, the Makefile will correctly reproduce the DEM-files. 

```
WGET=wget
WGETFLAGS=-N --ftp-user=anonymous --ftp-password=anonymous
URL=ftp://edcftp.cr.usgs.gov/data/gtopo30/global/

NAMES = antarcps e060n40 e100n40 e140n40 w020n40 w060n90 \
        w100n90 w140n90 w180s10 e020n40 e060n90 e100n90 \
        e140n90 w020n90 w060s10 w100s10 w140s10 w180s60 \
        e020n90 e060s10 e100s10 e140s10 w020s10 w060s60 \
        w120s60 w180n40 e020s10 e060s60 e120s60 w000s60 \
        w060n40  w100n40  w140n40  w180n90

ARCHIVES = $(addprefix gz/, $(NAMES:=.tar.gz))
HDR = $(addprefix data/, $(NAMES:=.hdr))
DEM = $(addprefix data/, $(NAMES:=.dem))

all: 

.SECONDARY:

gz/%.tar.gz:
	mkdir -p $(dir $@)
	$(WGET) $(WGETFLAGS) $(URL)$(notdir $@) -O $@.download
	mv $@.download $@

data/%.hdr: 
	mkdir -p $(dir $@)
	tar xzvk --transform 's/.*/\L&/' -f gz/$(notdir $(basename $@)).tar.gz -C data --wildcards '*.HDR'

data/%.dem: 
	mkdir -p $(dir $@)
	tar xzvk --transform 's/.*/\L&/' -f gz/$(notdir $(basename $@)).tar.gz -C data --wildcards '*.DEM'
	
fetch_dem: $(ARCHIVES)

extract_dem: fetch_dem $(HDR) $(DEM)

```

**Comment by nguy** [comment] 2015-03-06 22:38
@kmuehlbauer This is a really interesting solution.  If I"m reading this correctly, this downloads the data and puts it into a 'data' directory in the pyradarmet directory (though where does the addprefix come from?).  
I had come up with an alternative setup.py that still distributes the existing data and copies the data files that were downloaded to a separate location on the user system using a simple text file that can be modified if desired.  But, I'm not sure this is the most elegant solution and exactly how robust it is.

My first attempt to use a MANIFEST.in was not successful, partly due to keeping tracking of the data file location.  Below is a chunk of the script. 

```python
# Read the text file with location of where to install
demfiletxt = open('pyradarmet/demfile_locator.txt', 'r')
DEMInstall = demfiletxt.readline()
demfiletxt.close()
    
# Check for trailing directory "/"
if DEMInstall[-1] is not '/':
        DEMInstall = DEMInstall + '/'

#- Run setup
if DEMInstall == 'data/':
	setup(
		  name=PACKNAME,
		  version=VERSION,
		  url=URL,
		  author=AUTHOR,
		  author_email=EMAIL,
		  description=doclines[0],
		  license=LICENSE,
		  packages=PACKAGES,
		  package_data={PACKNAME: [DEMInstall+'*']},
		  include_package_data=True,
		  classifiers=["""
			Development Status :: 3 - Alpha,
			Programming Language :: Python",
			Topic :: Scientific/Engineering
			Topic :: Scientific/Engineering :: Atmospheric Science
			Operating System :: Unix
			Operating System :: POSIX :: Linux
			Operating System :: MacOS
			"""],
		   long_description = """
	A toolkit that contains a variety of utilities that can be used
	 to calculate fundamental radar meteorology values:

	* Convert between linear reflectivity(Z) and log reflectivity (dBZ)
	* Calculate coefficients for attenuation calculations
	* Calculate fundamental radar system characteristics
	* Calculate Doppler radar characteristics
	* Calculate geometrical characterisistics of radar
	* Calculate variables from radar output
	* Calculate ZDR bias of radar system""",
		  install_requires = ['Numpy >=1.7.2'],
		  )
else:
    print "In EXTERNAL"

    # Check for directory existence and create if necessary
    if not (os.path.isdir(DEMInstall)):
        os.makedirs(DEMInstall)
    for demfile in os.listdir(DEMDIR):
        print "Copying to " + DEMInstall + demfile
        copyfile(DEMDIR + "/" + demfile, DEMInstall + demfile)

    setup(
		  name=PACKNAME,
		  version=VERSION,
		  url=URL,
		  author=AUTHOR,
		  author_email=EMAIL,
		  description=doclines[0],
		  license=LICENSE,
		  packages=PACKAGES,
		  classifiers=["""
			Development Status :: 3 - Alpha,
			Programming Language :: Python",
			Topic :: Scientific/Engineering
			Topic :: Scientific/Engineering :: Atmospheric Science
			Operating System :: Unix
			Operating System :: POSIX :: Linux
			Operating System :: MacOS
			"""],
		   long_description = """
	A toolkit that contains a variety of utilities that can be used
	 to calculate fundamental radar meteorology values:

	* Convert between linear reflectivity(Z) and log reflectivity (dBZ)
	* Calculate coefficients for attenuation calculations
	* Calculate fundamental radar system characteristics
	* Calculate Doppler radar characteristics
	* Calculate geometrical characterisistics of radar
	* Calculate variables from radar output
	* Calculate ZDR bias of radar system""",
		  install_requires = ['Numpy >=1.7.2'],
		  )
```

**Comment by kmuehlbauer** [comment] 2015-03-10 07:12
@nguy 
Yes in general it downloads the data and decompresses the needed files to a data-folder below the "Makefile".

We have the $NAMES variable with all needed gtopo30-tiles (only basename). Then we create a $ARCHIVE variable by adding ".tar.gz" to the end of all $NAMES elements and prepending it with the prefix "gz/" for the folder where the archive-files should exist.  Similar we create $HDR and $DEM variables for the .dem and .hdr files.

So we have the variable lists as follows (only first member):

$Names |  $ARCHIVES | $HDR | $DEM
------------ | ------------- | ------- | ------- 
antarcps | gz/antarcps.tar.gz |  data/antarcps.hdr | data/antarcps.dem

Following that we have the four "make"-commands. If we call this "Makefile" with `make extract_dem` then it works on this line:

`extract_dem: fetch_dem $(HDR) $(DEM)`

First it will work on the `fetch_dem` command:

`fetch_dem: $(ARCHIVES)`

This will take the $ARCHIVES variable list and iterate over its members, trying to "make" something out of it. This is handled by this line:

```
gz/%.tar.gz:
    mkdir -p $(dir $@)
    $(WGET) $(WGETFLAGS) $(URL)$(notdir $@) -O $@.download
    mv $@.download $@
```
If if finds the given file at the location (gz/antarcps.tar.gz) nothing will be done. If the file is missing, the three lines are executet. This will create a "data"-folder if there isn't one (hence the $(dir $@) which gets just the "gz"-directory). Then it will download the file (antarcps.tar.gz) and move it in place.

If the $ARCHIVES variable list is finished, the `extract_dem` command will go to the next variable $(HDR):

```
data/%.hdr: 
	mkdir -p $(dir $@)
	tar xzvk --transform 's/.*/\L&/' -f gz/$(notdir $(basename $@)).tar.gz -C data --wildcards '*.HDR'
```
It iterates over the $HDR variable list and if the files are not present it will execute the two lines. First create data-folder if neccessary. Then extract the ".HDR" file. The files are all uppercase in the tarball so we have to give the `--transform` switch to create lower-case output. The `-f` switch gives the archive ("gz/antarcps.tar.gz") and the `-C` switch the output-folder ("data"). The `--wildcards` switch is needed to extract only '*.HDR' files.

Last the $DEM variable is worked on similar to the $HDR.

If all files are in place, `make extract_dem` will come up with a message, that it is nothing to do for this target. If you would delete one file, it will be recreated by "make-ing".

I must confess, that I have only shallow knowledge of "make" and "Makefiles" and adapted this functionality from other web-resources.

**Comment by kmuehlbauer** [comment] 2015-03-10 08:48
Anyway, for the Makefile approach you need Linux environment, or similar. So a pure python approach seems most reasonable to reach all users.

**Comment by kmuehlbauer** [comment] 2015-03-10 11:10
Pure python:  

```python
import urllib2
import shutil
import os
import tarfile
import time

gtopourl="ftp://edcftp.cr.usgs.gov/data/gtopo30/global/"

basefolder="/work/radproc/data/radar/gtopo30"
archfolder=os.path.join(basefolder, 'gz')
datafolder=os.path.join(basefolder, 'data')

names =["antarcps", "e060n40", "e100n40", "e140n40", "w020n40", "w060n90",
        "w100n90", "w140n90", "w180s10", "e020n40", "e060n90", "e100n90",
        "e140n90", "w020n90", "w060s10", "w100s10", "w140s10", "w180s60",
        "e020n90", "e060s10", "e100s10", "e140s10", "w020s10", "w060s60",
        "w120s60", "w180n40", "e020s10", "e060s60", "e120s60", "w000s60",
        "w060n40", "w100n40", "w140n40", "w180n90"]
        
for folder in [archfolder, datafolder]:
  if not os.path.exists(folder):
    os.makedirs(folder)

start_time = time.time()
    
for filename in names:
  archfilebase = filename+".tar.gz"
  archfile = os.path.join(archfolder, archfilebase)
  hdrfilebase = filename+".hdr"
  demfilebase = filename+".dem"
  
  if not os.path.exists(archfile):
    print("downloading: {0}".format(archfilebase))
    ftpfile = urllib2.urlopen(gtopourl+archfilebase)
    localfile = open(archfile, "wb")
    shutil.copyfileobj(ftpfile, localfile)
    localfile.close()
  
  for exfilebase in [hdrfilebase, demfilebase]:
    exfile = os.path.join(datafolder,exfilebase)
    if not os.path.exists(exfile):
      print("extracting: {0} from {1}".format(exfilebase, archfilebase))
      tar = tarfile.open(archfile)  
      tarobj = tar.extractfile(exfilebase.upper())
      localfile = open(exfile, "wb")
      shutil.copyfileobj(tarobj, localfile)
      tarobj.close()
      localfile.close()
      tar.close()
     
elapsed_time = time.time() - start_time
print(elapsed_time)
```

**Comment by kmuehlbauer** [comment] 2015-03-10 11:43
@nguy 

Anyway how the data finds it's way into a particular directory, one robust way to declare this directory in the sources is via an environment variable. This variable can be checked from within python using `os.getenv` or `os.environ`. 

So, there are two use cases:

1. install data to default folder
no env variable defined

2. let the user specify the data folder
env variable should be defined (e.g GTOPO_DATA) pointing to the data directory

In Beamblock.py the existence of GTOPO_DATA can be checked this way:

```python
try:
  DEM_DATADIR = os.environ["GTOPO_DATA"]
except KeyError:
  DEM_DATADIR = os.sep.join([os.path.dirname(__file__), 'data'])
```

But setting this variable correctly is one thing the user has to do... Sorry for this extension of this issue. Hopefully you can make some use of it at least...

**Comment by nguy** [comment] 2015-03-19 02:57
@kmuehlbauer  - Sorry for the delay.  Finally got to this today.  (Had some computer issues).

Great suggestions.  I've implemented the pure python with slight modifications where applicable.  

@tjlang - Try out the new install if you get a chance.  This should take care of the large files and with @kmuehlbauer solution, an auto download.

**Comment by nguy** [comment] 2015-03-27 14:39
Okay, it appears that this issue is now closed, so closing.  Thanks for the help @tjlang and @kmuehlbauer !

**Closed by nguy** 2015-03-27 14:39 UTC
